import "./globals.css";
import { Roboto_Slab } from "next/font/google";
const roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Cricket Score",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
